services:
  postgres:
    image: postgres:16-alpine
    container_name: aryes-db
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aryes_v2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: